apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{.Values.specialresource.metadata.name}}
  name: {{.Values.specialresource.metadata.name}}
spec: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: empty-certs
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{.Values.specialresource.metadata.name}}
  name: {{.Values.specialresource.metadata.name}}
  annotations:
    specialresource.openshift.io/kernel-affine: "true"
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    images:
    {{- range $image := .Values.specialresource.spec.driverContainer.artifacts.images }}
    - from:
        kind: {{$image.kind}}
        name: {{$image.name}}
        namespace: {{$image.namespace}}
      {{ range $path := $image.path }}
      paths:
        - sourcePath: {{ $path.sourcePath }}
          destinationDir: {{ $path.destinationDir }}
      {{ end }}
    {{- end }}
    {{- if eq .Values.signDriver true }}
    secrets:
    - secret:
        name: signing-key
      destinationDir: "./signing-keys/"
    {{- else }}
    configMaps:
      - configMap:
          name: empty-certs
        destinationDir: "./signing-keys/"
    {{- end }}
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile-ice-driver.SRO
      buildArgs:
        {{- range $arg := .Values.buildArgs }}
        - name: {{ $arg.name }}
          value: {{ $arg.value }}
        {{- end }}
        {{- if .Values.kernelVersion }}
        - name: "KVER"
          value: {{.Values.kernelVersion}}
        {{- else }}
        - name: "KVER"
          value: {{.Values.kernelFullVersion}}
        {{- end }}
        - name: "SIGN_DRIVER"
        {{- if .Values.signDriver }}
          value: "true"
        {{- else }}
          value: "false"
        {{- end }}
        - name: "DOWNLOAD_DRIVER"
        {{- if .Values.downloadDriver }}
          value: "true"
        {{- else }}
          value: "false"
        {{- end }}

  output:
    pushSecret:
      name: external-registry
    to:
      kind: DockerImage
      {{- if .Values.kernelVersion }}
      name: {{.Values.externalRegistry}}/{{.Values.containerName}}:{{.Values.kernelVersion}}
      {{- else }}
      name: {{.Values.externalRegistry}}/{{.Values.containerName}}:{{.Values.kernelFullVersion}}
      {{- end }}

